spring:
  liquibase:
    enabled: false
  h2:
    console:
      enabled: true
  datasource:
    name: test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb?mode=MySQL
  sql:
    init:
      mode: always
    init-platform: h2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update