aws:
  dynamodb:
    region: ${AWS_DYNAMO_DB_REGION:}
    endpoint: https://dynamodb.${AWS_DYNAMO_DB_REGION:}.amazonaws.com
  credentials:
    access-key-id: ${AWS_DYNAMO_DB_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_DYNAMO_DB_SECRET_ACCESS_KEY:}
