liquibase:
  enabled: false
  change-log=classpath: /db/changelog/db.changelog-master.yaml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/afetdb?createDatabaseIfNotExist=true
    username: root
    password: ippavlova_1990
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  description: Afet Yönetim Sistemi Tanımı (AYS)
  version: 1.0
