server:
  port: 9790

logging:
  level:
    web: debug

spring:
  liquibase:
    enabled: true
    changeLog: "classpath:db/changelog/db.changelog-master.yaml"
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

ays:
  db:
    name: mysql
    username: ${AYS_DB_USERNAME:ays}
    password: ${AYS_DB_PASSWORD:ayspass}
    url: jdbc:mysql://${AYS_DB_IP:localhost}:${AYS_DB_PORT:3306}/ays
    maximum-pool-size: 5
    connection-timeout: 180000
    maximum-lifetime: 170000

springdoc:
  packagesToScan: com.ays
  cache:
    disabled: false
  swagger-ui:
    path: /public/api/swagger-ui.html
  api-docs:
    path: /public/api/docs