spring:
  liquibase:
    enabled: true
    changeLog: "classpath:db/changelog/db.changelog-master.yaml"
  datasource:
    url: jdbc:mysql://localhost:3306/afetdb?createDatabaseIfNotExist=true
    username: root
    password: ippavlova_1990
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  description: Afet Yönetim Sistemi Tanimi (AYS)
  version: 1.0
  title: "AYS"
  licenseName: AYS Licence


ays:
  token:
    secret: afet-secret
    expires-in: 120000  # 2 minutes
    refresh-token-expires-in: 120000 # 2 minutes
