server:
  port: 9790

logging:
  level:
    web: debug

application:
  description: Afet Yönetim Sistemi (AYS)
  version: 1.0.0
  title: AYS
  licenseName: AYS Licence

spring:
  liquibase:
    enabled: true
    changeLog: "classpath:db/changelog/db.changelog-master.yaml"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

ays:
  db:
    name: mysql
    maximum-pool-size: 5
    connection-timeout: 180000
    maximum-lifetime: 170000

springdoc:
  swagger-ui:
    path: /swagger-ui.html