name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update package cache
        run: sudo apt-get update

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean install
        id: maven-build

      - name: Deploy to server
        if: steps.maven-build.success
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}
          PATH: ${{ secrets.BACKEND_PATH }}
        run: |
          bash ./build/deploy.sh