# Purpose: This file is used to build the project when a pull request is opened, reopened, edited, synchronized, ready for review, or unlocked.
name: Pull Request Checker

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - unlocked

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #      - name: Update package cache
      #        run: sudo apt-get update
      #
      - name: Checkout code
        uses: actions/checkout@v3
      #
      #      - name: Set up Java
      #        uses: actions/setup-java@v3
      #        with:
      #          java-version: 17
      #          distribution: 'zulu'

      #      - name: Install Maven
      #        run: sudo apt-get install -y maven
      #
      #      - name: Copy settings.xml file from template
      #        run: cp template-settings.xml settings.xml
      #
      #      - name: Replace username in settings.xml
      #        run: sed 's|'{YOUR_GITHUB_USERNAME}'|'${{ secrets.GH_USERNAME }}'|g' settings.xml >> temp-settings.xml ; rm settings.xml ; mv temp-settings.xml settings.xml
      #
      #      - name: Replace access token in settings.xml
      #        run: sed 's|'{YOUR_PERSONAL_GITHUB_ACCESS_TOKEN}'|'${{ secrets.GH_USER_ACCESS_TOKEN }}'|g' settings.xml >> temp-settings.xml ; rm settings.xml ; mv temp-settings.xml settings.xml
      #
      #      - name: Build with Maven
      #        run: mvn --settings settings.xml clean install
      #        id: maven-build

      - name: Deploy to server
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
          AWS_TEST_ENVIRONMENT_IP: ${{ secrets.AWS_TEST_ENVIRONMENT_IP }}
          AWS_BE_APP_PATH: ${{ secrets.AWS_BE_APP_PATH }}
          GH_TEST_DEPLOYMENT_BRANCH: ${{ env.GH_TEST_DEPLOYMENT_BRANCH }}
        run: bash .github/workflows/test/deploy.sh